require 'user.launch'
require 'user.options'
require 'user.keymaps'
require 'user.autocmd'

Spec 'user.colorscheme'
Spec 'user.statusline'
Spec 'user.lsp'
Spec 'user.syntax'
Spec 'user.cmp'
Spec 'user.find'
Spec 'user.git'
Spec 'user.filetree'
Spec 'user.shortcuts'

require 'user.lazy'
